### PR TITLE
Fix the "go get" installation instructions

### PR DESCRIPTION
**Pull request by scottjbarr**
A minor doc fix

### CODE REVIEW

**Comment by scottjbarr** [comment]
Hi @ClaytonWong . Is my PR no good?

**Comment by jsmith-dev** [comment]
Attn: *Scott Barr*
Re: *Sorrry! We didn't mean that*

Hi Scott,

Further to our discussion,

   - Can you re-open your pull-request?

I look forward to your advice.

Kind Regards,
​
Julian Smith
Founder, CEO
+1 (415) 815-3924 <(415)%20815-3924>
Blockfreight, Inc. <https://blockfreight.com/>

*Office | +1 (415) 429-3924 <+14154293924>*
*US Cell | *+1 (415) 815-8368 <+14158158368>

Blockfreight, Inc.
535 Mission St 14th floor
San Francisco CA 94105

www.blockfreight.com | julian.smith@blockfreight.com

*Book-A-Video-Call: | *https://calendly.com/blockfreight/chat/

*Disclaimer: *This email has been sent on the condition that the
recipient/client agrees and acknowledges that the email may contain
material that is confidential and/or covered by legal professional
privilege and is intended for the named recipient. Blockfreight, Inc. does
not warrant that the contents of any electronically transmitted information
is accurate and will remain confidential. If the reader of this email is
not the intended recipient you are hereby notified that any use,
reproduction, disclosure or distribution of the information contained in
the email is prohibited. If you receive this email in error, please reply
to the sender immediately and delete the document. No warranty is made that
this material is free from computer virus or any other defect or error.

**Comment by scottjbarr** [comment]
Hi Julian

Not sure how the PR was closed. Happy for you to re-open it :)

Cheers
Scott

**Comment by jsmith-dev** [comment]
Ok

**Pull request closed without merging**
